### ISSUE TITLE
Canvas height problem (resize)

### ISSUE THREAD

**Issue by EmpireDemocratiqueDuPoulpe** [visjs/vis-network#101]
Hi,

I'm having a strange bug with vis-network _(last version)_ and the canvas. I'm using **Firefox Developer Edition** on **Windows 7**. Here is a preview:

![1vis](https://user-images.githubusercontent.com/45202304/63921484-2db58080-ca43-11e9-88ae-6de5d0c3b3d7.png)
![2vis](https://user-images.githubusercontent.com/45202304/63921498-3312cb00-ca43-11e9-93a2-a5c11d897e4f.png)

We can see that the container is exactly the same size as the canvas. The `AutoResize` property is set to false, the width and height are set to `100%`. From the initialization, we can see that the canvas has 4 size properties.

![3vis](https://user-images.githubusercontent.com/45202304/63921739-a9afc880-ca43-11e9-8db7-8d2a12107951.PNG)

I have a button used to enable/disable physics. Every time I press this button, the canvas height is increased by 10px/20px. `height: 100%` does not work any more and the canvas can grow indefinitely.
```JS
this.physics.click(function (e) {

    if (!defaultButtonAction(e, $(this).parent())) return;

    Network.setOptions({physics: {enabled: !Network.physics.physicsEnabled}});
});
```

![4vis](https://user-images.githubusercontent.com/45202304/63922243-981af080-ca44-11e9-91ba-2b78b4bd037c.png)

So I write a function called on `afterRedraw` event. I use `sizes.oldWidth` and `sizes.oldHeight` as parameter.

```JS
[...]
element: $(".vis-network canvas);
resize: function(w = "500px", h = "500px") {

    if (this.element) this.element.width(w).height(h);
},
[...]
```

But now when I press the button, the canvas height switch between `503px` and `506px`. So, when the canvas height is `503px`, there is a line never cleared between the canvas and the container.

![5vis](https://user-images.githubusercontent.com/45202304/63922721-8554eb80-ca45-11e9-85a6-e7e0ec84b84e.png)

It would be better to be able to use `height: 100%` instead of forcing the canvas to keep the same `px` size. Do you have any idea how to make height fixed without `px` ?

**Comment by Thomaash** [comment]
Hi @EmpireDemocratiqueDuPoulpe, isn't this the same problem as #89? Doesn't this solution help: https://github.com/visjs/vis-network/issues/89#issuecomment-524575105 ?

**Comment by EmpireDemocratiqueDuPoulpe** [comment]
Hi @Thomaash,
I'm not sure it's the same problem. Here is the HTML:

```HTML
<!-- Before vis-js init -->
<div id="network-container">
</div>

<!-- After vis-js init -->
<div id="network-container">
    <div class="vis-network" style="position: relative; overflow: hidden; touch-action: pan-y; user-select: none; width: 100%; height: 100%;" tabindex="900">
        <canvas style="position: relative; touch-action: none; user-select: none; width: 784px; height: 503px;" width="784" height="506"></canvas>
    </div>
    <div id="zoom">0.62/10</div>
</div>
```
This is the CSS:
```CSS
#network-container {
    position: relative;
    flex-grow: 1;
    /*border: 2px #F44336 solid;*/
    border-radius: 5px;
    -webkit-box-shadow: inset 0px 0px 22px 0px rgba(0,0,0,0.38);
    -moz-box-shadow: inset 0px 0px 22px 0px rgba(0,0,0,0.38);
    box-shadow: inset 0px 0px 22px 0px rgba(0,0,0,0.38);
}

#zoom {
    position: absolute;
    right: 5px;
    bottom: 0;
    font-size: 0.6rem;
    pointer-events: none;
}
```

When I create the network, the canvas is slightly smaller than the container. If I manually change the size of the canvas with the console, the container also grows. It's very weird.

**Comment by Thomaash** [comment]
Doesn't happen to me: https://jsfiddle.net/thomaash/1secrxdj/ . Could you provide an MWE please?

**Comment by EmpireDemocratiqueDuPoulpe** [comment]
We can see the problem without pressing the button: https://jsfiddle.net/wymhxrug/
I have removed everything not needed.

**Comment by Thomaash** [comment]
Hmm, it seems to be related to flex in Firefox.

**Comment by EmpireDemocratiqueDuPoulpe** [comment]
Well, I forced the canvas height in `px`. Thanks for your help!

**Comment by Thomaash** [comment]
Having `display: flex` in the outer container and `overflow: hidden` in the inner container at the same time triggers this in Firefox.

```html
<div class="inner">
  <div class="outer">
    <canvas/>
  </div>
</div>
```

Not using flex makes this issue dissappear as well as the following (I'm not sure about consequences though):
```css
.vis-network {
  overflow: visible !important;
}
```
