### ISSUE TITLE
Sizing diagram 100% width and height

### ISSUE THREAD

**Issue by PrzemyslawKlys** [visjs/vis-network#167]
I have this code: https://codepen.io/MadBoyEvo/pen/ExxNvmo

When loaded DataTables first load as a big table, and then paging kicks in getting it resized to "expected" values. However, it seems that Vis-network stays as it was when the page first opened up.

![image](https://user-images.githubusercontent.com/15063294/67151157-d3f26980-f2c1-11e9-8224-d086089cc00b.png)

```css
 .diagram {
                min-height: 400px;
                width: 100%;
                height: 100%;
                border: 0px solid unset;
            }
```

Is there a way to size Vis-network properly in such a situation? If I change the height to a static value, and then the table on the left is bigger the Diagram doesn't fill the full space.

![image](https://user-images.githubusercontent.com/15063294/67151194-701c7080-f2c2-11e9-9ffc-a979b3bb24ff.png)

```css
   .diagram {
                min-height: 400px;
                width: 100%;
                height: 600px;
                border: 0px solid unset;
            }
```
Do you think one can control it in some way? Redraw based on DataTables redraw?
