### ISSUE TITLE
Window autoresizes itself in Firefox

### ISSUE THREAD

**Issue by PrzemyslawKlys** [visjs/vis-network#628]
I have a weird issue that was initially reported in my repo; https://github.com/EvotecIT/PSWriteHTML/issues/113

The diagram resizes itself in Firefox (and only in Firefox) working properly in all other browsers.

![AutoSizeProblem](https://user-images.githubusercontent.com/15063294/79101039-07d9b380-7d68-11ea-81fa-cee54be86061.gif)

Here's the codepen showing issue. 

https://codepen.io/MadBoyEvo/pen/XWmbZra

No refresh is necessary.

**Comment by Thomaash** [comment]
The code's giant and I don't have the time to read it right now, but isn't this just CSS issue? The same as #89?

**Comment by PrzemyslawKlys** [comment]
Hi, I've removed unnecessary stuff leaving only 148 lines mostly for readability. 

I tried applying code from the linked issue but whatever I do doesn't help. Granted - I am CSS noob.

Relevant code:

```css
        <style type="text/css">
            .defaultSection {
                border: 1px solid #bbbbbb;
                padding-bottom: 0px;
                margin: 5px;
                width: calc(100% - 10px);
            }

            .overflowHidden {
                overflow: hidden;
                overflow-x: hidden;
                overflow-y: hidden;
            }

            .flexParent {
                display: flex;
                justify-content: space-between;
                padding: 2px;
            }

            .flexParentInvisible {
                display: flex;
                justify-content: space-between;
            }

            .flexElement {
                flex-basis: 100%;
            }

            .flexPanel {
                flex-basis: 100%;
            }

            .roundedCorners {
                box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
                transition: 0.3s;
                border-radius: 5px;
                margin: 5px;
            }
        </style><!-- CSS Always Required Default Visual Settings END -->
```

And html
```html
        <div data-panes="true">
            <div id="Tab-ta6f7ijb-Content" class="active">
                <div class="defaultSection roundedCorners overflowHidden">
                    <div class="defaultHeader" style="text-align:center;background-color:#00bfff"><a name="Test" style="color: #ffffff;">Test </a><a id="show_505656775" href="javascript:void(0)" onclick="show('505656775');" style="color: #ffffff; display:none;">(Show)</a><a id="hide_505656775" href="javascript:void(0)" onclick="hide('505656775');" style="color: #ffffff; display:none;">(Hide)</a></div>
                    <div id="505656775" class="flexParent flexElement overflowHidden">
                        <div id="505656775" class="flexParent flexElement overflowHidden collapsable">
                            <div id="Diagram-hvardq4p" class="diagram"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
```
